<<<<<<< HEAD
name: CI - Build & Test

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
=======
name: Continuous Integration (CI)

on:
  push:
    branches: [ manajemen-produk ]
  pull_request:
    branches: [ manajemen-produk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
>>>>>>> manajemen-produk
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
<<<<<<< HEAD
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
=======
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
>>>>>>> manajemen-produk

      - name: Build with Gradle
        run: ./gradlew build

<<<<<<< HEAD
      - name: Run Tests
        run: ./gradlew test
=======
      - name: Run tests
        run: ./gradlew test
>>>>>>> manajemen-produk
